### PR TITLE
Fixes known issues in the crowdsale demo

### PR DESCRIPTION
**Pull request by WyattMufson**
**What current issue(s) from Github does this address?**
#98 #99

**What problem does this PR solve?**
Adds OnTransfer to the minting in the deploy function and fixes total supply. Also makes sure that the nep5 functions are checking that the arguments are in the right format

**How did you solve this problem?**
#98 and #99 are pretty self explanatory. Length check for addresses for the argument formatting issue

**How did you make sure your solution works?**
Standardized it with the standalone NEP5 demo and another contract that I've tested on my private net

**Are there any special changes in the code that we should be aware of?**
No

**Is there anything else we should know?**
The NEP5 demo has slightly different code than the one in the crowdsale demo. They should probably be fully standardized in the future

### CODE REVIEW

**Comment by WyattMufson** [comment]
Looks like some of the tests are failing (like one due to the use of `totalSupply` over `circulation`). Fixing these now and will commit the updates tests.

**Comment by WyattMufson** [comment]
Now also is meant to address #101 and #102

**Comment by WyattMufson** [comment]
Interested in getting feedback on this^

**Comment by localhuman** [comment]
Looks good, thanks for the changes!

I would only add that the demo is only for compiler testing purposes and shouldn't be confused for something that is a production ready NEP5 token.

**Comment by WyattMufson** [comment]
@localhuman is there an example of a place with a production ready NEP5 contract? The [awesome-neo repo](https://github.com/CityOfZion/awesome-neo/blob/master/resources/python-examples.md#code-examples) lists these contracts and the [ICO-Templates repo](https://github.com/CityOfZion/ICO-Templates) is empty so far. Would it make sense to put some of this there?

**Pull request merged**
