### PR TITLE
Added logzero to requirements

### PR DESCRIPTION
**Pull request by igormcoelho**
**What current issue(s) from Github does this address?**

**What problem does this PR solve?**
logzero dependency is missing, see file:  neo-boa/boa/code/pytoken.py

**How did you solve this problem?**
Followed the instructions to install neo-boa, installed logzero manually with pip, and included it with the corresponding version to the project.

**How did you make sure your solution works?**
I know this works because it works online at https://neocompiler.io

**Are there any special changes in the code that we should be aware of?**

**Is there anything else we should know?**

### CODE REVIEW

**Comment by igormcoelho** [comment]
Oh my, why has it failed? O.o
I don't understand the result (which tests have failed).

**Comment by metachris** [comment]
it failed not because of your PR, but because it uses a now non-existing branch in travis ci. Going to open a PR.

    error: pathspec 'feature-36

**Comment by metachris** [comment]
Should be fixed with this: https://github.com/CityOfZion/neo-boa/pull/49

**Comment by igormcoelho** [comment]
Ok, I'll try again soon :)

**Comment by localhuman** [comment]
I think the main problem is you're trying to make a PR to the master branch. @metachris made the fix on the `development` branch.  

I tried switching the target of this PR to `development`, but it seems like travis is not picking up that change.

Could you close this PR, and make a new one with your change against the development branch, then I think the tests will pass :)

**Comment by localhuman** [comment]
Had to make another update, so added this change in 17cb8fb0ff6f83df235cb31a74b4ec49c4e4ec99

**Pull request closed without merging**
