### PR TITLE
Added support for Neo debugger map file generation

### PR DESCRIPTION
**Pull request by Relfos**
This adds support for generation of debug map files for the Neo debugger, using the new json format (*.debug.json), which allows the debugger to map lines from a .py source file to the .avm opcodes.

Here's an example of a debug map generated by neo-boa:

```json
{
    "compiler": {
        "name": "neo-boa",
        "version": "0.1"
    },
    "files": [
        {
            "url": "D:\\code\\Crypto\\neo-boa\\boa\\tests\\src/AddTest.py",
            "id": "1"
        }
    ],
    "avm": {
        "name": "AddTest",
        "hash": "c485df80dc0551162a344ed1617956e5"
    },
    "map": [
        {
            "start": 17,
            "end": 43,
            "file": 1,
            "line": 10
        },
        {
            "start": 44,
            "end": 61,
            "file": 1,
            "line": 11
        },
        {
            "start": 62,
            "end": 88,
            "file": 1,
            "line": 13
        },
        {
            "start": 89,
            "end": 100,
            "file": 1,
            "line": 14
        }
    ]
}
```

### CODE REVIEW

**Comment by localhuman** [comment]
🥇 This is awesome! Is it ok if I change the PR to the `development` branch?

**Comment by Relfos** [comment]
Sure, change :)

**Comment by localhuman** [comment]
Try running `pycodestyle boa` to make sure the style passes.  You should be able to fix most of the style issues if not all of them with `autopep8 --in-place --recursive boa`

**Comment by localhuman** [comment]
Thanks again, this is great work :)

**Pull request merged**
