### PR TITLE
Fix abi returntype casing

### LINKED ISSUE #135: Visual DevTracker deploy function not detecting contracts compiled with neo-boa
AVM files compiled with neo-boa are not being detected in the Visual DevTracker due to incorrect casing in the abi.json output. This prevents contracts being deployed from the UI and breaks a lot of  other functionality (e.g invocation interface) as a result.

### PR DESCRIPTION
**Pull request by EdgeDLT**
**What current issue(s) from Github does this address?**
Fix #135

**What problem does this PR solve?**
Fixes incorrect casing in .abi.json output so that it matches the Neon compiler output, improving compatibility with the Neo Blockchain Toolkit's Visual DevTracker.

**How did you solve this problem?**
Changed a big T to a little t.

**How did you make sure your solution works?**
Tested neo-boa contract detection in Visual DevTracker deploy menu before and after the change.

**Are there any special changes in the code that we should be aware of?**
Nope.

### CODE REVIEW

**Comment by meevee98** [comment]
Can you also update unit tests, please?

**Comment by ixje** [comment]
@EdgeDLT I understand the fix is for Visual DevTracker, but does this break deploying from `neo-cli` or have they updated it there as well? If so, will this mean that it will only work for e.g. `neo-cli 2.11` or is it backwards compatible with `2.10.3`? his question is mainly to understand if we should put a warning in the release notes. Thanks

As for the request from @meevee98 , she's referring to this
```
======================================================================
ERROR: test_abi_method_without_return_type (tests.test_abi_methods.TestContract)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/CityOfZion/neo-boa/boa_test/tests/test_abi_methods.py", line 117, in test_abi_method_without_return_type
    self.assertEqual(main_function['returnType'], 'Void')
KeyError: 'returnType'
======================================================================
ERROR: test_abi_methods_only_entry_point (tests.test_abi_methods.TestContract)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/CityOfZion/neo-boa/boa_test/tests/test_abi_methods.py", line 78, in test_abi_methods_only_entry_point
    self.assertEqual(main_function['returnType'], 'Any')
KeyError: 'returnType'
======================================================================
ERROR: test_abi_methods_success (tests.test_abi_methods.TestContract)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/CityOfZion/neo-boa/boa_test/tests/test_abi_methods.py", line 22, in test_abi_methods_success
    self.assertEqual(main_function['returnType'], 'Any')
KeyError: 'returnType'
----------------------------------------------------------------------
```

@meevee98 once we merge this

**Comment by EdgeDLT** [comment]
@ixje as far as I'm aware this has been the standard format used by neo-cli for some time, nothing should have changed between 2.10.3 and 2.11.0. This output matches the [NEP-3 standard](https://github.com/neo-project/proposals/blob/dappstandard/nep-3.mediawiki#function).

**Comment by ixje** [comment]
I'll take it. Thanks!

**Pull request merged**
